#!/usr/bin/env bash
#slm
# shellcheck disable=SC2009

# Get the PID of the Bash process
pid=$(ps aux | grep bash | grep -v grep | awk '{print $2}')

# Display the PID
echo "PID of the Bash process: $pid"
