#!/usr/bin/env bash
#slm

# Search for processes containing the word "bash" and extract their PID and process name
pids=$(pgrep -f bash)

# Iterate over the PIDs and display the PID and process name
for pid in $pids; do
  
        process_name=$(ps -p "$pid" -o comm=)
        echo "$pid $process_name"
    
done
