#!/usr/bin/env bash
#bashable clock

Hour=0
minutes=1
while [ "$Hour" -lt 13 ]; do
      echo "Hour: $Hour" 
      while [ "$minutes" -lt 60 ]; do
      	    echo "$minutes"
	    ((minutes++))
      done
      minutes=1
      ((Hour++))
done
