#!/usr/bin/env bash
#slm
file="school"

# Check if the file exists
if [ -e "$file" ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ -s "$file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "$file" ]; then
        echo "school is a regular file"
    else
        # If the file is not a regular file (e.g., a directory or symbolic link), do nothing
        :
    fi
else
    echo "school file does not exist"
fi
