#!/usr/bin/env bash
#checks if a file exists

school="school"

if [ -e "$school" ]; then
   echo "school file exists"
   
   if [ -s "$school" ]; then
      echo "school file is not empty"
   else
      echo "file is empty"
   fi
   
   if [ -f "$school" ]; then
      echo "school file is a regular file"
   else
      :
   fi
else
   echo "school file does not exist"
fi
